# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-21 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casino',
            new_name='CasinoModel',
        ),
    ]
