# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-21 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2app', '0002_auto_20190522_0149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='RestaurantModel',
        ),
        migrations.RenameModel(
            old_name='TableGame',
            new_name='TableGameModel',
        ),
    ]
