# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-22 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2app', '0003_auto_20190522_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='casino',
            field=models.ManyToManyField(to='assignment2app.CasinoModel'),
        ),
        migrations.AddField(
            model_name='tablegamemodel',
            name='casino',
            field=models.ManyToManyField(to='assignment2app.CasinoModel'),
        ),
    ]
