# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-22 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2app', '0004_auto_20190522_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinomodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
